//
//  TipsVC.m
//  WealthTracker
//
//  Created by Rick Medved on 9/17/15.
//  Copyright (c) 2015 Rick Medved. All rights reserved.
//

#import "TipsVC.h"

@interface TipsVC ()

@end

@implementation TipsVC

-(void)viewWillAppear:(BOOL)animated
{
	[super viewWillAppear:animated];
	if([self respondsToSelector:@selector(edgesForExtendedLayout)])
		[self setEdgesForExtendedLayout:UIRectEdgeBottom];
	
}

- (void)viewDidLoad {
	[super viewDidLoad];
	[self setTitle:@"Strategy Guide"];
	
	if(self.type==1) // real estate
		self.textView.text = @"\"The best investment on earth is earth.\"\n-Louis Glickman\n\n\"A man complained that every day he had to pass through that long field of his neighbor’s.  I advised him to buy it, and it would never seem long again.\"\n-Ralph Waldo Emerson\n\n\"The major fortunes in America have been made in land.\"\n -John D. Rockefeller\n\n\"I would give a thousand furlongs of sea for an acre of barren ground.\"\n-Shakespeare\n\n\"Landlords grow rich in their sleep.\"\n-John Stuart Mill\n\n\"Buying real estate is not only the best way, the quickest way, the safest way, but the only way to become wealthy.\"\n-Marshall Field\n\n\"Real estate provides the highest returns, the greatest values and the least risk.\"\nArmstrong Williams\n\nThose are some great quotes! The thing to remember about real estate is that there are smart ways to buy homes and, well, not-so smart ways. If you purchase real estate at a high interest rate and most or all of your monthly payment is going towards interest, this is NOT a wise purchase.\n\nThe only way real estate becomes an asset to you is when it has equity. Your goal should be to improve that equity at the fastest rate possible. That means getting the lowest interest rate possible, and then paying off the balance.\n\nA 15 year loan will always give you a better interest rate than a 30 year loan, which means a 15 year loan is always a better investment for you. If your goal is to build wealth, you need to be smart with your money.\n\nBanks will try to talk you into 30 year loans and the reason? Because it makes them lots of money! Keep that money in your own pocket and go with a 15 year loan instead.\n\nCan't afford it? Then shop for a smaller home, or continue saving up money for a larger down payment. The key is to be smart with your money.\n\nTips for home buying:\n*Always finance with 15 year loan (or less)\n*Never own rental property until your home is paid off.\n*Buy with 20% down to avoid PMI.\n*Avoid making any large purchases just prior to home shopping.\n*For price comparisons, use actual sale prices, not 'for sale' list prices.\n\n\"There's blind luck, dumb luck and then there's get up every morning at 5:30 and sweat the details luck. In the end, luck has very little to do with success. \"";
	if(self.type==2) // auto
		self.textView.text = @"\"If GM had kept up with technology like the computer industry has, we would all be driving $25 cars that got 1,000 MPG.\"\n-Bill Gates\n\n\"Let someone else take the butt kicking on devaluation.\"\n-Dave Ramsey\n\nThe secret to building wealth as related to vehicles is: Always pay cash for your cars. Avoid financing and never lease!\n\nThe reason is because cars, unlike homes, depreciate over time. Over-spending on vehicles is a tragic mistake when it comes to wealth building.\n\nWhen people finance vehicles, they tend spend WAY out of their budget, and are then saddled with large monthly payments (and interest payments) for years to come. Plus insurance is much higher and depreciation is more extreme with new cars as well. You need to break out of this cycle.\n\nVehicles do NOT build wealth, they consume it. So you should only be purchasing one out of your excess wealth-- which means paying cash. Keep in mind, we don't say, 'Never buy a new car'. If you are doing well with your money and have the cash in the bank, feel free to buy the car you want. As long as you are paying cash, you can always feel good about your purchase. You deserve it!\n\nWhat if you don't have any cash? Your best bet is to get a low cost beater for $1500 and then start saving up for a nicer car. It's not as much fun, but it means paying $0 in interest and losing close to $0 in depreciation. In fact, a car that you buy for $1500 will often sell for the same price a year later. You get all your money back! In the end, your wealth is much stronger going this route.\n\nTips for car buying:\n* Always pay cash for your cars. Avoid finance and never lease.\n* If you do finance, never drive it home until the paperwork is finalized. Avoid the 'Your financing fell through' scams.\n* Never get involved with co-sign loans - ever, for any reason. period.\n* Never trade in a vehicle with a balance. Pay off your balance first.\n* Never negotiate around a monthly payment. Only for the final price.\n* Don’t buy unneeded extras. Like corrosion protection or fabric protection.\n* Don’t buy extended warranties.\n\n\"Most of the things we buy are wants. We call them needs, but they are wants.\"\n- Dave Ramsey";
	if(self.type==3) // debts
		self.textView.text = @"\"We buy things we don't need with money we don't have to impress people we don't like.\"\n- Dave Ramsey\n\n\"The borrower is slave to the lender.\"\n -The Bible\n\n\"The man who never has money enough to pay his debts has too much of something else.\"\n -James Lendall Basford\n\n\"Never spend your money before you have it.\"\n -Thomas Jefferson\n\n\"Today, there are three kinds of people:  the have’s, the have-not’s, and the have-not-paid-for-what-they-have’s.\"\n -Earl Wilson\n\nYou get the idea. The point is you want to get out of debt. You can't build wealth while you are paying a large portion of your paycheck on interest.\n\nThe first step in building wealth is to reduce your interest payments and start climbing out of debt. It is a tough road to go down, but it's necessary if you want to win with money.\n\nGo through the plan on the main menu screen and look for tips on how to climb your way out.\n\nBe very careful how you spend your money and do not overextend yourself.\n\n\"Too many people try to do the new job, new spouse, new house, new car thing in 18 months. That's a good way to end up broke. We've got to resist the temptation to catch up with our parents in 18 months. Slow down. You have the rest of your life to play catch up. After all, it's just stuff.\"\n- Dave Ramsey ";
	if(self.type==4) // wealth
		self.textView.text = @"\"Right now I have enough money to last me the rest of my life - unless I buy something.\"\n- Jackie Mason\n\n\"Financial peace isn't the acquisition of stuff. It's learning to live on less than you make, so you can give money back and have money to invest. You can't win until you do this.\"\n — Dave Ramsey\n\n\"Live like no one else today, so you can live like no one else tomorrow.\"― Dave Ramsey\n\nThis means live off less today and pay down your debts, while all your friends are buying expensive cars and going on expensive vacations, so that in your later years, you will be able to live more abundantly than your neighbors who are in over their heads in debt.\n\nWealth, or net worth, is defined as what you own minus what you owe. As in, your assets minus your debts. For far too many people, unfortunately, this is a negative number. Your goal is to get this number up. WAY up!\n\nThere are two ways your wealth grows: through assets appreciating and by paying down debts. Since you have no control over the rate of appreciation of your assets, the most tangible way you have of gaining wealth is to pay down your debts.\n\nBeing smart with your money should always be on your mind. This means not wasting it on junk and, instead, making wise purchases at all times.\n\nCareful budgeting and planning is the most important tool in gaining control of your money. Get in the habit of paying your bills first, and then live on whatever is left over. That's the simplest way to budget. Going with an envelope system where every dollar has a name is even better, but requires a lot of work. Find a system that works well for you.\n\n\"If a man has money, it is usually a sign too, that he knows how to take care of it; don't imagine his money is easy to get simply because he has plenty of it.\"\n- Edgar Watson Howe";
	
}


@end
